name: tests

on: [push, pull_request]

jobs:
  ci:
    name: Test on PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', '8.1', '8.2']
        laravel: [8, 9, 10]
        exclude:
          - php: 8.0
            laravel: 10
          - php: 8.2
            laravel: 8
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, pdo, pdo_mysql, bcmath, swoole
          tools: phpize
          coverage: none
      - name: Install dependencies
        run: |
          composer require "laravel/framework:^${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress
      - name: Run Cs Fixer
        run: |
          if [ "${{ matrix.php }}" = "8.2" ]; then
            PHP_CS_FIXER_IGNORE_ENV=true php vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
          else
            php vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
          fi
      - name: Run Analyse
        run: |
          # composer analyse src
          php vendor/bin/phpstan analyse --memory-limit 300M -l 0 -c phpstan.neon ./src
      # - name: Run Test Cases
      #   run: |
      #     composer test