name: tests

on: [push, pull_request]

env:
  PHP_CS_FIXER_IGNORE_ENV: 1

jobs:
  ci:
    name: Test on PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.1', '8.2']
        laravel: [10]
        # exclude:
        #   - php: 8.0
        #     laravel: 10
      max-parallel: 4
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, pdo, pdo_mysql, bcmath, swoole
          tools: phpize
          coverage: none
      - name: Install Dependencies
        run: |
          composer require "laravel/framework:^${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress
      - name: Run Cs Fixer
        run: |
          php vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
      - name: Run Analyse
        run: |
          php vendor/bin/phpstan analyse --memory-limit 300M -l 0 -c phpstan.neon ./src
      - name: Run Test Cases
        run: |
          composer test
      - name: Setup Redis
        run: |
          docker run -d -p 6379:6379 redis
      - name: Setup Laravel App
        run: |
          PROJECT_NAME=laravel
          echo "Creating Laravel Project: ${PROJECT_NAME}"
          composer create-project --prefer-dist laravel/laravel ${PROJECT_NAME} ^${{ matrix.laravel }}
          cd ${PROJECT_NAME}

          echo "Installing laravel/horizon"
          composer require laravel/horizon
          php artisan horizon:install

          echo "Installing huangdijia/laravel-horizon-restart"
          composer config repositories.laravel-horizon-restart path ../
          composer require huangdijia/laravel-horizon-restart

          echo "Booting Horizon"
          php artisan horizon &

          sleep 5

          echo "Checking Horizon"
          php artisan horizon:status

          echo "Restart Horizon"
          php artisan horizon:restart

          echo "Checking Horizon"
          php artisan horizon:status

          sleep 5

          echo "Checking Horizon"
          php artisan horizon:status