name: PHPUnit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

env:
  PHP_CS_FIXER_IGNORE_ENV: 1

jobs:
  ci:
    name: Test on PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.1', '8.2', '8.3']
        laravel: [10, 11]
        exclude:
          - php: 8.1
            laravel: 11
      max-parallel: 36
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, pdo, pdo_mysql, bcmath
          tools: phpize
          coverage: none
      - name: Install Dependencies
        run: |
          composer require "laravel/framework:^${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress
      - name: Run Cs Fixer
        run: |
          php vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
      - name: Run Analyse
        run: |
          php vendor/bin/phpstan analyse --memory-limit 300M -l 0 -c phpstan.neon ./src
      - name: Run Test Cases
        run: |
          composer test
